RustLangES/rust-book-es

- src/ch00-00-introduction.md
- src/ch01-01-installation.md
- src/ch01-02-hello-world.md
- src/ch01-03-hello-cargo.md
- src/foreword.md
> Homogeneizando el estilo, y pequeñas correcciones

- src/ch04-03-slices.md
añadí una traducción del capítulo de los slices aunque algunas cosas preferí dejarlas en ingles como los chapter debido a que aún no me acostumbro a como funciona el libro y no quiero romper algo accidentalmente. Por cierto, ¿como puedo ejecutar el libro localmente para comprobar que no se haya roto nada?
> Añadiendo traducción de los slices

- src/ch05-01-defining-structs.md
Añadí una traducción del Inglés al Español del capítulo 5.1 de los structs
> Añadiendo traducción al Español

- src/ch05-02-example-structs.md
Añadí una traducción del capítulo 5.2
> Añadiendo traducción del capítulo 5.2

- src/ch05-03-method-syntax.md
Añadí la traducción al Español del capítulo 5.3 sintaxis de métodos
> Añadiendo traducción del capítulo 5.3

- src/ch06-00-enums.md
- src/ch06-01-defining-an-enum.md
- src/ch06-02-match.md
- src/ch06-03-if-let.md
Traduje los capítulos
* 6-00
* 6-01
* 6-02
* 6-03
Del libro de Rust
> Traducción de los capítulos de los enums

- src/ch09-00-error-handling.md
- src/ch09-01-unrecoverable-errors-with-panic.md
- src/ch09-02-recoverable-errors-with-result.md
- src/ch09-03-to-panic-or-not-to-panic.md
Añadí la traducción del capítulo 9 del libro
> Traducción del capítulo 9

- src/ch11-00-testing.md
- src/ch12-00-an-io-project.md
- src/ch13-00-functional-features.md
- src/ch14-00-more-about-cargo.md
- src/ch14-04-installing-binaries.md
- src/ch14-05-extending-cargo.md
- src/ch17-00-oop.md
- src/ch18-00-patterns.md
- src/ch19-00-advanced-features.md
- src/ch20-00-final-project-a-web-server.md
Hice la traducción de los capítulos más cortos para acortar tiempo
> Traducción de los capítulos con poco texto

- src/ch10-00-generics.md
- src/ch10-01-syntax.md
- src/ch10-02-traits.md
- src/ch10-03-lifetime-syntax.md
Hice la traducción de los capítulos 10
> Traducción de los capítulos 10

- src/ch11-01-writing-tests.md
- src/ch11-02-running-tests.md
- src/ch11-03-test-organization.md
Hice la traducción de los capítulos 11 sobre testing en Rust
> Traducción de los capítulos 11

- src/ch13-01-closures.md
- src/ch13-02-iterators.md
- src/ch13-03-improving-our-io-project.md
- src/ch13-04-performance.md
He realizado al traducción de los capítulos 13 del libro
> Traducción de los capítulos 13

- src/ch14-01-release-profiles.md
- src/ch14-02-publishing-to-crates-io.md
- src/ch14-03-cargo-workspaces.md
Traduje los capítulos 14 restantes
> Traducción de los capítulos 14

- src/ch15-00-smart-pointers.md
- src/ch15-01-box.md
- src/ch15-02-deref.md
- src/ch15-03-drop.md
- src/ch15-04-rc.md
- src/ch15-05-interior-mutability.md
- src/ch15-06-reference-cycles.md
hice la traducción de los capítulos 15
> Traducción de los capítulos 15

- src/ch18-00-patterns.md
- src/ch18-01-all-the-places-for-patterns.md
- src/ch18-02-refutability.md
- src/ch18-03-pattern-syntax.md
Hice la traducción del capítulo 18 acerca de los patterns en Rust (**Se necesita revisión**)
> Traducción de los capítulos 18

- src/ch20-01-single-threaded.md
- src/ch20-02-multithreaded.md
Hice la traducción del capítulo 20 al 20-02
> Traducción de los capítulos 20

- src/SUMMARY.md
Fix the error on the titltes of those chapters by modifiying the `SUMMARY.md`
> fix(ui): Chapter 11.2 Title Translation Error

- src/ch20-03-graceful-shutdown-and-cleanup.md
Hice la traducción del último capítulo del libro
> Traducción del capítulo 20-03 del libro

- src/appendix-03-derivable-traits.md
Hice la traducción del apéndice-03 del libro
> Traducción del apéndice-03 del libro

- src/appendix-04-useful-development-tools.md
Traducción del Apéndice 04 del libro
> Appendix 04

- src/ch10-03-lifetime-syntax.md
corrigiendo errores ortográficos
> ✏️ fix: fix typos

- .github/workflows/sitemap.yml
el bendito sitemap 😏 
- el diagrama informal de alto nivel esta acá arriba 👆
- acá sólo checamos si hay cambios en el src para los md files
- los posibles problemas y soluciones estan marcados con el mismo color en el diagrama
- comentar por aca, si no se entiende o mejor aún si hay algún cambio, es más facil modificar el diagrama: https://excalidraw.com/#json=3WjyGq26navNFA_6ST0Fd,MtXXo_sCj0VeW6OfTswl-g
- los otros workflows:
- https://github.com/RustLangES/blog/pull/15
- https://github.com/RustLangES/rust-book-es/pull/42
- el repo del sitemap: https://github.com/ph4un00b/sitemap-rustico
> ci: sitemap workflow

- src/ch03-01-variables-and-mutability.md
This PR fixes some typos and small grammatical errors in chapter 3.1
> fix: typos and small grammatical errors in chapter 3.1

- src/ch02-00-guessing-game-tutorial.md
- src/ch03-02-data-types.md
- src/ch19-01-unsafe-rust.md
- src/title-page.md
fix small grammatical errors and improved readability in chapter 3.2
> fix: small grammatical errors and improved readability in chapter 3.2

- src/ch03-03-how-functions-work.md
fixed small grammatical errors and improved readability in chapter 3.3
> fix: small grammatical errors and improved readability in chapter 3.3

- src/ch03-05-control-flow.md
Fixed small grammatical errors and improved readability in chapter 3.5
> fix: small grammatical errors and improved readability in chapter 3.5

- ci/dictionary.txt
- src/ch04-01-what-is-ownership.md
- src/ch04-02-references-and-borrowing.md
- src/ch04-03-slices.md
fix: improve readability and translations in chapter 4
> fix: improve readability and translations in chapter 4

- src/ch04-02-references-and-borrowing.md
changed markdown words starting with underscore to asterisk in
chapter 4.2
> chore: changed markdown words starting with underscore to asterisk in chapter 4.2

- src/ch05-02-example-structs.md
- src/ch05-03-method-syntax.md
fix: improved readability and traslations in chapter sections 5.2 and 5.3
> fix: improved readability and traslations in chapter sections 5.2 and 5.3

- src/ch09-01-unrecoverable-errors-with-panic.md
- src/ch09-02-recoverable-errors-with-result.md
fix: improve readability and translation in chapter 9
> fix: improve readability and translation in chapter 9

- src/ch10-00-generics.md
- src/ch10-01-syntax.md
- src/ch10-02-traits.md
- src/ch10-03-lifetime-syntax.md
improve chapter 10 readability and added missing code example
> feat: improve chapter 10 readability and added missing code example

- flake.lock
- flake.nix
This pull request adds a flake.nix, to be declaratively cool
> Add nix flake!

- src/ch18-01-all-the-places-for-patterns.md
- src/ch18-03-pattern-syntax.md
- src/ch19-00-advanced-features.md
- src/ch19-05-advanced-functions-and-closures.md
- src/ch19-06-macros.md
Ensured consistency in the translation of key concepts across multiple chapters.
> Refactor typo + consistent
